### PR TITLE
Add Post Notification

### PR DESCRIPTION
**Pull request by apocm**
## Request for Change

[Notification API GA: Update Postman collection](https://zendesk.atlassian.net/browse/SCE-365)

Priority : `low` 
Impact : `low` 
Risk : `low` 
Classification : `preauthorized` 
Security impact: None 

Automated tests: N/A
Manual tests: N/A 

Expected deployment date/time : 2020-04-01 AM 
Expected downtime duration : 0 minutes
Rollout plan & rollback instructions: Revert github files and push to master

### CODE REVIEW

**Comment by alexibz** [comment]
In the body it shows up that there's the author role in the root of the json,
```
    "author": {
    	"role": "appMaker"
    },
```
but in the bug bash card it was under message:
```
"message": {
    "type": "text",
    "text": "Check this out!",
    "role": "appMaker"
  }
```
Do both methods work?

**Comment by alexibz** [comment]
Also, the update to the dev postman account will be I guess after merging this PR?
https://github.com/smooch/smooch#updating-smooch-api-postman-collection

**Comment by apocm** [comment]
> In the body it shows up that there's the author role in the root of the json,
> 
> ```
>     "author": {
>     	"role": "appMaker"
>     },
> ```
> 
> but in the bug bash card it was under message:
> 
> ```
> "message": {
>     "type": "text",
>     "text": "Check this out!",
>     "role": "appMaker"
>   }
> ```
> 
> Do both methods work?

@alexibz 
Yes, both work. role can be in either - but is required as a part of author when sending WhatsApp Message Templates. Figured I'd just add author to make it simpler when deciding to send templates.

> Also, the update to the dev postman account will be I guess after merging this PR?

I've made the changes in the dev postman account... have they not synched? I'm at step 5 in the directions.

**Review by maleblond — APPROVED** [review]

**Review by tunguyennnnn — APPROVED** [review]

**Comment by alexibz** [comment]
**EDIT: I needed to go to Team > Sunshine Conversations to see the new endpoint 🤦‍♂** 


> I've made the changes in the dev postman account... have they not synched? I'm at step 5 in the directions.

Hmmmm, no don't see them. Have you pressed sync?
image

**Review by alexibz — APPROVED** [review]

**Pull request merged**
