### PR TITLE
Added Merge User request and fixed Unlink Users

### PR DESCRIPTION
**Pull request by alexibz**
## Request for Change

**Description and reason for the change**
**EDIT: Updated the PR based on the new way of updating the postman collection.**
Added a missing Merge User request and updated the Unlinking of the channel request, addressing the following tickets:
https://zendesk.atlassian.net/browse/SCBE-360 and
https://zendesk.atlassian.net/browse/SCBE-362

Automated tests: 
N/A

Manual tests : 
Ran the requests against local environment

Expected deployment date/time : 2020-02-05 PM   
Expected downtime duration : 0 minutes  
[Rollout plan & rollback instructions](../tree/master/deployment)  
Database migration rollout & rollback plan: N/A

### CODE REVIEW

**Comment by DataWearsAHood** [comment]
@alexibz 
sorry, tons of questions:
- Was this auto-generated? (Might explain a few things...)
- How come the description texts were removed from `Get Integration Menu`?
- How come a bunch of the objects seem to have swapped places? (Get Integration Menu [#2], [Not] Using Passthrough Api, Image with text <-> Image Example, etc.)

**Comment by alexibz** [comment]
The file was exported from Postman and a lot of the information get's garbled up - I think it's more worth it to look at try out the collection in real life, because the diff can be confusing when exporting from different Postman versions.

**Review by Mario54 — APPROVED** [review]

**Review by tunguyennnnn — APPROVED** [review]

**Review by davesmooch — DISMISSED** [review]

**Comment by davesmooch** [comment]
I think description is missing the normal stuff like impact, rollback, etc

**Comment by alexibz** [comment]
Updated the info. By default didn't have the template here in this repo.

**Review by jmtremblay — APPROVED** [review]

**Comment by alexibz** [comment]
Updated the postman collection based on the new steps involved in releasing it.

**Review by Mario54 — APPROVED** [review]

**Pull request merged**
