### PR TITLE
formatting/character corrections in "ABC - Large Interactive"

### PR DESCRIPTION
**Pull request by DataWearsAHood**
## Request for Change

Visual improvement in example

Priority : `low` 
Impact : `low` 
Risk : `low` 
Classification : `preauthorized` 
Security impact: None 

Automated tests: N/A
Manual tests: N/A 

Expected deployment date/time : 2020-06-11 PM
Expected downtime duration : 0 minutes
Rollout plan & rollback instructions: Revert github files and push to master

### CODE REVIEW

**Comment by alexibz** [comment]
@DataWearsAHood I tried to download and import the raw collection file but postman was complaining that it was an incorrect format. Did you export the file as a 2.1 collection?
image

**Comment by DataWearsAHood** [comment]
I only made the text-edits in the repo directly 😬
Did that break stuff?

**Comment by alexibz** [comment]
Yea, postman is finicky with editing the JSON directly. Is the only change the removal of the extra `\n` ?

**Comment by DataWearsAHood** [comment]
Yes - there was a dozen or so of them on that one line.
Also 2 stylized double-quotes that broke JSON rules.

**Comment by alexibz** [comment]
Can you make changes to the latest collection and export it from Postman and then upload it.

**Review by alexibz — APPROVED** [review]
👍  Looks good! A ton of changes in the diff - but that's just postman being postman.

**Review by apocm — APPROVED** [review]

**Comment by alexibz** [comment]
Just a PSA: you would also need to update the collection in 2 other places: the team account and the postman "marketplace": https://github.com/smooch/smooch#updating-smooch-api-postman-collection

**Pull request merged**
